# Generated by Django 4.1.3 on 2023-04-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_delete_bookitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_at", models.DateTimeField(blank=True, null=True)),
                ("return_by", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_items",
                        to="books.book",
                    ),
                ),
                (
                    "borrowed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="borrowed_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
