# Generated by Django 4.1.3 on 2023-04-09 17:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_bookitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookitems",
            name="book_item_id",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
