# Generated by Django 4.1.3 on 2023-04-09 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_bookitems_book_item_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookitems",
            options={"verbose_name": "Book Items"},
        ),
    ]
